export interface RegistryEntry {
  name: string
  type: 'registry:ui'
  sourceFile: string
  registryDependencies?: string[]
  dependencies?: string[]
  description?: string
}

export const REGISTRY: RegistryEntry[] = [
  {
    name: 'button',
    type: 'registry:ui',
    sourceFile: 'button.tsx',
    dependencies: ['@radix-ui/react-slot', 'class-variance-authority', 'clsx', 'tailwind-merge'],
    description: 'Gigaverse button — 8 variants incl. gold shimmer CTA, faction join, option card.',
  },
  {
    name: 'card',
    type: 'registry:ui',
    sourceFile: 'card.tsx',
    dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge'],
    description: 'Card with 6 variants: standard, tweet, strip, recessed, panel, stat.',
  },
  {
    name: 'input',
    type: 'registry:ui',
    sourceFile: 'input.tsx',
    dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge'],
    description: 'Text input with default / available / error states.',
  },
  {
    name: 'label',
    type: 'registry:ui',
    sourceFile: 'label.tsx',
    dependencies: ['@radix-ui/react-label', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'badge',
    type: 'registry:ui',
    sourceFile: 'badge.tsx',
    dependencies: ['@gigaverse/tokens', 'class-variance-authority', 'clsx', 'tailwind-merge'],
    description: 'Badge with rarity and faction variants.',
  },
  {
    name: 'separator',
    type: 'registry:ui',
    sourceFile: 'separator.tsx',
    dependencies: ['@radix-ui/react-separator', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'tabs',
    type: 'registry:ui',
    sourceFile: 'tabs.tsx',
    dependencies: ['@radix-ui/react-tabs', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'dialog',
    type: 'registry:ui',
    sourceFile: 'dialog.tsx',
    dependencies: ['@radix-ui/react-dialog', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'tooltip',
    type: 'registry:ui',
    sourceFile: 'tooltip.tsx',
    dependencies: ['@radix-ui/react-tooltip', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'toast',
    type: 'registry:ui',
    sourceFile: 'toast.tsx',
    dependencies: ['sonner', 'clsx', 'tailwind-merge'],
    description: 'Sonner-backed toaster themed for Gigaverse.',
  },
  {
    name: 'checkbox',
    type: 'registry:ui',
    sourceFile: 'checkbox.tsx',
    dependencies: ['@radix-ui/react-checkbox', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'radio-group',
    type: 'registry:ui',
    sourceFile: 'radio-group.tsx',
    dependencies: ['@radix-ui/react-radio-group', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'switch',
    type: 'registry:ui',
    sourceFile: 'switch.tsx',
    dependencies: ['@radix-ui/react-switch', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'slider',
    type: 'registry:ui',
    sourceFile: 'slider.tsx',
    dependencies: ['@radix-ui/react-slider', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'textarea',
    type: 'registry:ui',
    sourceFile: 'textarea.tsx',
    dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'toggle',
    type: 'registry:ui',
    sourceFile: 'toggle.tsx',
    dependencies: ['@radix-ui/react-toggle', 'class-variance-authority', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'toggle-group',
    type: 'registry:ui',
    sourceFile: 'toggle-group.tsx',
    registryDependencies: ['toggle'],
    dependencies: ['@radix-ui/react-toggle-group', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'popover',
    type: 'registry:ui',
    sourceFile: 'popover.tsx',
    dependencies: ['@radix-ui/react-popover', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'select',
    type: 'registry:ui',
    sourceFile: 'select.tsx',
    dependencies: ['@radix-ui/react-select', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'command',
    type: 'registry:ui',
    sourceFile: 'command.tsx',
    registryDependencies: ['dialog'],
    dependencies: ['cmdk', 'lucide-react', 'clsx', 'tailwind-merge'],
    description: 'Command palette (cmdk) with optional dialog wrapper.',
  },
  {
    name: 'combobox',
    type: 'registry:ui',
    sourceFile: 'combobox.tsx',
    registryDependencies: ['button', 'command', 'popover'],
    dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    description: 'Searchable single-select — popover + command palette + check icon.',
  },
  {
    name: 'form',
    type: 'registry:ui',
    sourceFile: 'form.tsx',
    registryDependencies: ['label'],
    dependencies: ['@radix-ui/react-label', '@radix-ui/react-slot', 'react-hook-form', 'clsx', 'tailwind-merge'],
    description: 'react-hook-form wrapper with FormField / FormItem / FormLabel / FormControl / FormMessage.',
  },
  {
    name: 'accordion',
    type: 'registry:ui',
    sourceFile: 'accordion.tsx',
    dependencies: ['@radix-ui/react-accordion', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'alert',
    type: 'registry:ui',
    sourceFile: 'alert.tsx',
    dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'alert-dialog',
    type: 'registry:ui',
    sourceFile: 'alert-dialog.tsx',
    dependencies: ['@radix-ui/react-alert-dialog', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'avatar',
    type: 'registry:ui',
    sourceFile: 'avatar.tsx',
    dependencies: ['@radix-ui/react-avatar', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'breadcrumb',
    type: 'registry:ui',
    sourceFile: 'breadcrumb.tsx',
    dependencies: ['@radix-ui/react-slot', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'calendar',
    type: 'registry:ui',
    sourceFile: 'calendar.tsx',
    dependencies: ['react-day-picker', 'date-fns', 'lucide-react', 'clsx', 'tailwind-merge'],
    description: 'Date calendar — react-day-picker wrapped in Gigaverse theme (gold selected, teal ranges).',
  },
  {
    name: 'date-picker',
    type: 'registry:ui',
    sourceFile: 'date-picker.tsx',
    registryDependencies: ['button', 'calendar', 'popover'],
    dependencies: ['date-fns', 'lucide-react', 'clsx', 'tailwind-merge'],
    description: 'Date picker — popover trigger with calendar content; bitcell display format.',
  },
  {
    name: 'dropdown-menu',
    type: 'registry:ui',
    sourceFile: 'dropdown-menu.tsx',
    dependencies: ['@radix-ui/react-dropdown-menu', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'context-menu',
    type: 'registry:ui',
    sourceFile: 'context-menu.tsx',
    dependencies: ['@radix-ui/react-context-menu', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'hover-card',
    type: 'registry:ui',
    sourceFile: 'hover-card.tsx',
    dependencies: ['@radix-ui/react-hover-card', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'menubar',
    type: 'registry:ui',
    sourceFile: 'menubar.tsx',
    dependencies: ['@radix-ui/react-menubar', 'lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'navigation-menu',
    type: 'registry:ui',
    sourceFile: 'navigation-menu.tsx',
    dependencies: [
      '@radix-ui/react-navigation-menu',
      'class-variance-authority',
      'lucide-react',
      'clsx',
      'tailwind-merge',
    ],
  },
  {
    name: 'pagination',
    type: 'registry:ui',
    sourceFile: 'pagination.tsx',
    dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'progress',
    type: 'registry:ui',
    sourceFile: 'progress.tsx',
    dependencies: ['@radix-ui/react-progress', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'scroll-area',
    type: 'registry:ui',
    sourceFile: 'scroll-area.tsx',
    dependencies: ['@radix-ui/react-scroll-area', 'clsx', 'tailwind-merge'],
  },
  {
    name: 'sheet',
    type: 'registry:ui',
    sourceFile: 'sheet.tsx',
    dependencies: [
      '@radix-ui/react-dialog',
      'class-variance-authority',
      'lucide-react',
      'clsx',
      'tailwind-merge',
    ],
  },
  {
    name: 'skeleton',
    type: 'registry:ui',
    sourceFile: 'skeleton.tsx',
    dependencies: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'table',
    type: 'registry:ui',
    sourceFile: 'table.tsx',
    dependencies: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'carousel',
    type: 'registry:ui',
    sourceFile: 'carousel.tsx',
    registryDependencies: ['button'],
    dependencies: ['embla-carousel-react', 'lucide-react', 'clsx', 'tailwind-merge'],
    description: 'Embla-backed carousel with prev/next arrows (gigaverse.io landing pattern).',
  },
  {
    name: 'tweet-carousel',
    type: 'registry:ui',
    sourceFile: 'tweet-carousel.tsx',
    dependencies: ['embla-carousel-react', 'clsx', 'tailwind-merge'],
    description:
      'Social quote carousel — auto-advance (6s), pauses on hover, gold-pill dot navigation.',
  },
  {
    name: 'giga-primitives',
    type: 'registry:ui',
    sourceFile: 'giga-primitives.tsx',
    dependencies: [
      '@gigaverse/tokens',
      'class-variance-authority',
      'clsx',
      'tailwind-merge',
    ],
    description:
      'Gigaverse-native primitives: StatusPip, PingPongLoader, FactionBadge, FactionJoinButton, RarityTag, ShimmerButton, AccentDivider, SectionDivider, StepProgress, StepProgressBar, StatBlock, SectionHeader, NumberedSectionHeader, LeftBorderAccent, CertificationRow, FactionPopulationCounter, SnapSection, EquipmentStrip, SectionAmbientPixels, LandingNavbar, LandingFooter.',
  },
  {
    name: 'giga-loader',
    type: 'registry:ui',
    sourceFile: 'giga-loader.tsx',
    dependencies: [
      '@dot-loaders/core',
      '@dot-loaders/presets',
      '@dot-loaders/react',
      'clsx',
      'tailwind-merge',
    ],
    description:
      'Unicode/braille dot loaders (~100 presets via @dot-loaders/react) themed for Gigaverse — GigaLoader, GigaLoaderInline, GigaLoaderOverlay, GigaLoaderProvider, GigaLoaderPicker.',
  },
  {
    name: 'landing-modal-shell',
    type: 'registry:ui',
    sourceFile: 'landing-modal-shell.tsx',
    registryDependencies: ['dialog'],
    dependencies: ['@radix-ui/react-dialog', 'lucide-react', 'clsx', 'tailwind-merge'],
    description:
      'LandingModalShell — branded Radix dialog with 3px teal/gold border, gradient header, and pixel close button.',
  },
]
